version: "2.0"
services:
    frontend:
        build: './frontend'
        ports:
            - 3000:3000

    backend:
        build: './backend'
        ports:
            - 5000:5000
        volumes:
            - "./backend/:/app/"
