version: "2.0"
services:
    backend:
        build: '.'
        ports:
            - 5000:5000
        hostname: "cloudera"
        extra_hosts:
            - "cloudera:127.0.0.1"
        volumes:
            - ".:/app/"
